services:
  frontend:
    image: frontend-development
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
    command: ["npm", "start"]
    environment:
      CI: true
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
    container_name: frontend-dev
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    image: backend-development
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/usr/src/app
    command: ["npm", "run", "dev"]
    environment:
      USRNAME: fullstack
      PASSWORD: 7MSAZ1cj1NwXZmad
    container_name: backend-dev
    ports:
      - 3001:3001
    